# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ericm/Documents/Classes/cpre583/final_project/LQR_Hardware/LQR_Hardware.srcs/sources_1/ip/floating_point_Multiplication_1/floating_point_Multiplication.xci
# IP: The module: 'floating_point_Multiplication' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ericm/Documents/Classes/cpre583/final_project/LQR_Hardware/LQR_Hardware.srcs/sources_1/ip/floating_point_Multiplication_1/floating_point_Multiplication_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'floating_point_Multiplication'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/ericm/Documents/Classes/cpre583/final_project/LQR_Hardware/LQR_Hardware.srcs/sources_1/ip/floating_point_Multiplication_1/floating_point_Multiplication.xci
# IP: The module: 'floating_point_Multiplication' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ericm/Documents/Classes/cpre583/final_project/LQR_Hardware/LQR_Hardware.srcs/sources_1/ip/floating_point_Multiplication_1/floating_point_Multiplication_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'floating_point_Multiplication'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
