# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/ericm/Documents/Classes/cpre583/final_project/LQR_Hardware/LQR_Hardware.cache/wt [current_project]
set_property parent.project_path /home/ericm/Documents/Classes/cpre583/final_project/LQR_Hardware/LQR_Hardware.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_output_repo /home/ericm/Documents/Classes/cpre583/final_project/LQR_Hardware/LQR_Hardware.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /home/ericm/Documents/Classes/cpre583/final_project/LQR_Hardware/LQR_Hardware.srcs/sources_1/new/LQR_Controller.vhd
  /home/ericm/Documents/Classes/cpre583/final_project/LQR_Hardware/LQR_Hardware.srcs/sources_1/imports/Eric_Code/shift_reg.vhd
  /home/ericm/Documents/Classes/cpre583/final_project/LQR_Hardware/LQR_Hardware.srcs/sources_1/imports/Eric_Code/dac.vhd
  /home/ericm/Documents/Classes/cpre583/final_project/LQR_Hardware/LQR_Hardware.srcs/sources_1/imports/Eric_Code/dac_clamp.vhd
  /home/ericm/Documents/Classes/cpre583/final_project/LQR_Hardware/LQR_Hardware.srcs/sources_1/imports/Eric_Code/lqr_fsm.vhd
  /home/ericm/Documents/Classes/cpre583/final_project/LQR_Hardware/LQR_Hardware.srcs/sources_1/imports/Eric_Code/meta_filter.vhd
  /home/ericm/Documents/Classes/cpre583/final_project/LQR_Hardware/LQR_Hardware.srcs/sources_1/imports/Eric_Code/quad_decoder.vhd
  /home/ericm/Documents/Classes/cpre583/final_project/LQR_Hardware/LQR_Hardware.srcs/sources_1/imports/Eric_Code/Top_Level.vhd
}
read_ip -quiet /home/ericm/Documents/Classes/cpre583/final_project/LQR_Hardware/LQR_Hardware.srcs/sources_1/ip/floating_point_Addition/floating_point_Addition.xci
set_property used_in_implementation false [get_files -all /home/ericm/Documents/Classes/cpre583/final_project/LQR_Hardware/LQR_Hardware.srcs/sources_1/ip/floating_point_Addition/floating_point_Addition_ooc.xdc]
set_property is_locked true [get_files /home/ericm/Documents/Classes/cpre583/final_project/LQR_Hardware/LQR_Hardware.srcs/sources_1/ip/floating_point_Addition/floating_point_Addition.xci]

read_ip -quiet /home/ericm/Documents/Classes/cpre583/final_project/LQR_Hardware/LQR_Hardware.srcs/sources_1/ip/floating_point_Float32_to_Int32/floating_point_Float32_to_Int32.xci
set_property used_in_implementation false [get_files -all /home/ericm/Documents/Classes/cpre583/final_project/LQR_Hardware/LQR_Hardware.srcs/sources_1/ip/floating_point_Float32_to_Int32/floating_point_Float32_to_Int32_ooc.xdc]
set_property is_locked true [get_files /home/ericm/Documents/Classes/cpre583/final_project/LQR_Hardware/LQR_Hardware.srcs/sources_1/ip/floating_point_Float32_to_Int32/floating_point_Float32_to_Int32.xci]

read_ip -quiet /home/ericm/Documents/Classes/cpre583/final_project/LQR_Hardware/LQR_Hardware.srcs/sources_1/ip/floating_point_Multiplication_1/floating_point_Multiplication.xci
set_property used_in_implementation false [get_files -all /home/ericm/Documents/Classes/cpre583/final_project/LQR_Hardware/LQR_Hardware.srcs/sources_1/ip/floating_point_Multiplication_1/floating_point_Multiplication_ooc.xdc]
set_property is_locked true [get_files /home/ericm/Documents/Classes/cpre583/final_project/LQR_Hardware/LQR_Hardware.srcs/sources_1/ip/floating_point_Multiplication_1/floating_point_Multiplication.xci]

read_ip -quiet /home/ericm/Documents/Classes/cpre583/final_project/LQR_Hardware/LQR_Hardware.srcs/sources_1/ip/floating_point_Int32_to_Float32_1/floating_point_Int32_to_Float32.xci
set_property used_in_implementation false [get_files -all /home/ericm/Documents/Classes/cpre583/final_project/LQR_Hardware/LQR_Hardware.srcs/sources_1/ip/floating_point_Int32_to_Float32_1/floating_point_Int32_to_Float32_ooc.xdc]
set_property is_locked true [get_files /home/ericm/Documents/Classes/cpre583/final_project/LQR_Hardware/LQR_Hardware.srcs/sources_1/ip/floating_point_Int32_to_Float32_1/floating_point_Int32_to_Float32.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/ericm/Documents/Classes/cpre583/final_project/LQR_Hardware/LQR_Hardware.srcs/constrs_1/new/LQR_Pinout.xdc
set_property used_in_implementation false [get_files /home/ericm/Documents/Classes/cpre583/final_project/LQR_Hardware/LQR_Hardware.srcs/constrs_1/new/LQR_Pinout.xdc]


synth_design -top Top_Level -part xc7z010clg400-1


write_checkpoint -force -noxdef Top_Level.dcp

catch { report_utilization -file Top_Level_utilization_synth.rpt -pb Top_Level_utilization_synth.pb }
