# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Matthew/Desktop/LQR_Vivado/LQR_Hardware/LQR_Hardware.srcs/sources_1/ip/floating_point_Float32_to_Int32/floating_point_Float32_to_Int32.xci
# IP: The module: 'floating_point_Float32_to_Int32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Matthew/Desktop/LQR_Vivado/LQR_Hardware/LQR_Hardware.srcs/sources_1/ip/floating_point_Float32_to_Int32/floating_point_Float32_to_Int32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'floating_point_Float32_to_Int32'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/Matthew/Desktop/LQR_Vivado/LQR_Hardware/LQR_Hardware.srcs/sources_1/ip/floating_point_Float32_to_Int32/floating_point_Float32_to_Int32.xci
# IP: The module: 'floating_point_Float32_to_Int32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Matthew/Desktop/LQR_Vivado/LQR_Hardware/LQR_Hardware.srcs/sources_1/ip/floating_point_Float32_to_Int32/floating_point_Float32_to_Int32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'floating_point_Float32_to_Int32'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
